<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOneThrough;
use Illuminate\Database\Eloquent\SoftDeletes;

class Effort extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'workspace_id',
        'initiative_id',
        'name',
        'code',
        'description',
        'auto_generated',
        'channel_type',
        'status',
        'executed_at',
    ];

    protected function casts(): array
    {
        return [
            'auto_generated' => 'boolean',
            'executed_at' => 'datetime',
        ];
    }

    // ── Relationships ────────────────────────────────────────────────

    public function workspace(): BelongsTo
    {
        return $this->belongsTo(Workspace::class);
    }

    public function initiative(): BelongsTo
    {
        return $this->belongsTo(Initiative::class);
    }

    public function program(): HasOneThrough
    {
        return $this->hasOneThrough(
            Program::class,
            Initiative::class,
            'id',        // initiatives.id
            'id',        // programs.id
            'initiative_id', // efforts.initiative_id
            'program_id'     // initiatives.program_id
        );
    }

    public function attributionKeys(): HasMany
    {
        return $this->hasMany(AttributionKey::class);
    }

    // ── Scopes ───────────────────────────────────────────────────────

    public function scopeAutoGenerated(Builder $query): Builder
    {
        return $query->where('auto_generated', true);
    }

    public function scopeManual(Builder $query): Builder
    {
        return $query->where('auto_generated', false);
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('status', 'active');
    }

    public function scopeForWorkspace(Builder $query, int|Workspace $workspace): Builder
    {
        $workspaceId = $workspace instanceof Workspace ? $workspace->id : $workspace;

        return $query->where('workspace_id', $workspaceId);
    }

    public function scopeForChannel(Builder $query, string $channelType): Builder
    {
        return $query->where('channel_type', $channelType);
    }
}
